import type { Device, MediaItem } from "@/types/media";

// Seed data for the stubbed API. Swap this module out (or point the API client
// at a real backend) without touching the UI layer.

export const seedDevices: Device[] = [
  {
    id: "dev-living-tv",
    name: "Living Room TV",
    kind: "tv",
    room: "Living Room",
    online: true,
    source: "HDMI 1",
    sources: ["HDMI 1", "HDMI 2", "Apps", "Antenna"],
  },
  {
    id: "dev-soundbar",
    name: "Sonos Arc",
    kind: "speaker",
    room: "Living Room",
    online: true,
    source: "TV (eARC)",
    sources: ["TV (eARC)", "Bluetooth", "AirPlay", "Spotify"],
  },
  {
    id: "dev-kitchen-speaker",
    name: "Kitchen Speaker",
    kind: "speaker",
    room: "Kitchen",
    online: true,
    source: "Spotify",
    sources: ["Spotify", "Bluetooth", "Radio"],
  },
  {
    id: "dev-bedroom-tv",
    name: "Bedroom TV",
    kind: "tv",
    room: "Bedroom",
    online: false,
    source: "HDMI 1",
    sources: ["HDMI 1", "Apps", "Antenna"],
  },
  {
    id: "dev-console",
    name: "Game Console",
    kind: "console",
    room: "Living Room",
    online: true,
    source: "Home",
    sources: ["Home", "Store", "Media"],
  },
  {
    id: "dev-receiver",
    name: "AV Receiver",
    kind: "receiver",
    room: "Living Room",
    online: true,
    source: "Optical",
    sources: ["Optical", "Coax", "Analog", "HDMI ARC"],
  },
];

export const seedLibrary: MediaItem[] = [
  {
    id: "med-1",
    title: "Neon Horizon",
    creator: "Ava Sterling",
    kind: "movie",
    genre: "Sci-Fi",
    year: 2024,
    duration: 7860,
    artwork: "from-fuchsia-600 to-indigo-700",
    rating: 4.6,
  },
  {
    id: "med-2",
    title: "Midnight Frequencies",
    creator: "The Glass Coast",
    kind: "music",
    genre: "Synthwave",
    year: 2023,
    duration: 224,
    artwork: "from-cyan-500 to-blue-700",
    rating: 4.8,
  },
  {
    id: "med-3",
    title: "The Quiet Mountain",
    creator: "Noor Rahimi",
    kind: "show",
    genre: "Drama",
    year: 2025,
    duration: 2940,
    artwork: "from-emerald-500 to-teal-700",
    rating: 4.3,
  },
  {
    id: "med-4",
    title: "Deep Field",
    creator: "Orbital Theory",
    kind: "podcast",
    genre: "Science",
    year: 2026,
    duration: 3120,
    artwork: "from-amber-500 to-orange-700",
    rating: 4.1,
  },
  {
    id: "med-5",
    title: "Crimson Tides",
    creator: "Dario Vance",
    kind: "movie",
    genre: "Thriller",
    year: 2022,
    duration: 6720,
    artwork: "from-rose-600 to-red-800",
    rating: 4.0,
  },
  {
    id: "med-6",
    title: "Golden Hour",
    creator: "Lena Park",
    kind: "music",
    genre: "Indie Pop",
    year: 2024,
    duration: 198,
    artwork: "from-yellow-400 to-pink-600",
    rating: 4.7,
  },
  {
    id: "med-7",
    title: "Signal Lost",
    creator: "Keiko Tanaka",
    kind: "show",
    genre: "Mystery",
    year: 2025,
    duration: 3300,
    artwork: "from-violet-600 to-purple-800",
    rating: 4.5,
  },
  {
    id: "med-8",
    title: "Tidal Drift",
    creator: "Wavelength",
    kind: "music",
    genre: "Ambient",
    year: 2023,
    duration: 312,
    artwork: "from-sky-500 to-indigo-700",
    rating: 4.2,
  },
  {
    id: "med-9",
    title: "The Long Build",
    creator: "Makers Daily",
    kind: "podcast",
    genre: "Tech",
    year: 2026,
    duration: 2760,
    artwork: "from-slate-500 to-zinc-700",
    rating: 3.9,
  },
];
